# Generated by Django 6.0.1 on 2026-01-20 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_options_alter_offerdetail_options'),
        ('orders', '0003_alter_order_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='offers.offerdetail'),
        ),
    ]
